name: manual workflow

on:
  workflow_dispatch: 
   inputs:
      name:
      description: 'Name'
      type: string
      default: 'test'

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Hello World directly
      - name: Print Hello World
        run: echo "Hello, World!"
